import type { AppRoute } from "@/shared/types/AppRoute.type";
import {
  IconCalendar,
  IconChartBar,
  IconCreditCard,
  IconDashboard,
  IconShieldLock,
  IconSettings,
  IconShieldCheck,
  IconUsers,
} from "@tabler/icons-react";

export const appRoutes: AppRoute[] = [
  {
    label: "Inicio",
    path: "",
    icon: IconDashboard,
    showInSidebar: true,
  },
  {
    label: "Perfil",
    path: "profile",
    icon: IconUsers,
    showInSidebar: false,
  },
  {
    label: "Miembros",
    path: "users",
    icon: IconUsers,
    module: "users",
    permissions: ["users.read"],
    showInSidebar: true,
  },
  {
    label: "Cobros",
    path: "billing",
    icon: IconCreditCard,
    module: "billing",
    permissions: ["billing.read"],
    showInSidebar: true,
  },
  {
    label: "Horarios",
    path: "schedules",
    icon: IconCalendar,
    module: "schedules",
    permissions: ["schedules.read"],
    showInSidebar: true,
  },
  {
    label: "Roles",
    path: "rbac",
    icon: IconShieldCheck,
    module: "settings",
    permissions: ["roles.manage"],
    showInSidebar: true,
  },
  {
    label: "Analitica",
    path: "analytics",
    icon: IconChartBar,
    module: "analytics",
    permissions: ["analytics.read"],
    showInSidebar: true,
  },
  {
    label: "Auditoria",
    path: "audit",
    icon: IconShieldLock,
    module: "audit",
    permissions: ["audit.read"],
    showInSidebar: true,
  },
  {
    label: "Configuracion",
    path: "settings",
    icon: IconSettings,
    module: "settings",
    permissions: ["settings.read"],
    showInSidebar: true,
  },
];
